// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA8w2eKNM_7NHTxKEPonqXhdjRDl5YYUY',
    appId: '1:34322017082:web:a7dc48a6c146b865397e03',
    messagingSenderId: '34322017082',
    projectId: 'lawcompanyapp',
    authDomain: 'lawcompanyapp.firebaseapp.com',
    storageBucket: 'lawcompanyapp.firebasestorage.app',
    measurementId: 'G-HRRBZRB92Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAxAjAoeybaKn1kKsiC2pl9KSj20YDHWg',
    appId: '1:34322017082:android:7bc0a5c5adc0a224397e03',
    messagingSenderId: '34322017082',
    projectId: 'lawcompanyapp',
    storageBucket: 'lawcompanyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4h-mUw0PCaj7SG-RUauTIx3SJ_-PaznA',
    appId: '1:34322017082:ios:0314f6996ee06d2e397e03',
    messagingSenderId: '34322017082',
    projectId: 'lawcompanyapp',
    storageBucket: 'lawcompanyapp.firebasestorage.app',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4h-mUw0PCaj7SG-RUauTIx3SJ_-PaznA',
    appId: '1:34322017082:ios:0314f6996ee06d2e397e03',
    messagingSenderId: '34322017082',
    projectId: 'lawcompanyapp',
    storageBucket: 'lawcompanyapp.firebasestorage.app',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA8w2eKNM_7NHTxKEPonqXhdjRDl5YYUY',
    appId: '1:34322017082:web:8e204e1444885ed8397e03',
    messagingSenderId: '34322017082',
    projectId: 'lawcompanyapp',
    authDomain: 'lawcompanyapp.firebaseapp.com',
    storageBucket: 'lawcompanyapp.firebasestorage.app',
    measurementId: 'G-DCZYKB2BDJ',
  );
}
