// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB8IGTzvDtXMr4UO1K0Bj48vJybIaAj4Ok',
//     appId: '1:459786430343:web:a693ff516f55027eec9522',
//     messagingSenderId: '459786430343',
//     projectId: 'notification-test-20bf1',
//     authDomain: 'notification-test-20bf1.firebaseapp.com',
//     storageBucket: 'notification-test-20bf1.firebasestorage.app',
//     measurementId: 'G-9DT1MQ9LZG',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAs0fzrSw2WfKdQIS6wkiOdd6e8vzXKHcg',
//     appId: '1:459786430343:android:c36087a7e26fe19cec9522',
//     messagingSenderId: '459786430343',
//     projectId: 'notification-test-20bf1',
//     storageBucket: 'notification-test-20bf1.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCD-JUPv7EVaIX6BrM_OJGlCc12S_1id7k',
//     appId: '1:459786430343:ios:f7ded4f83182bc65ec9522',
//     messagingSenderId: '459786430343',
//     projectId: 'notification-test-20bf1',
//     storageBucket: 'notification-test-20bf1.firebasestorage.app',
//     iosBundleId: 'com.example.untitled30',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCD-JUPv7EVaIX6BrM_OJGlCc12S_1id7k',
//     appId: '1:459786430343:ios:f7ded4f83182bc65ec9522',
//     messagingSenderId: '459786430343',
//     projectId: 'notification-test-20bf1',
//     storageBucket: 'notification-test-20bf1.firebasestorage.app',
//     iosBundleId: 'com.example.untitled30',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyB8IGTzvDtXMr4UO1K0Bj48vJybIaAj4Ok',
//     appId: '1:459786430343:web:47578ee4e7204821ec9522',
//     messagingSenderId: '459786430343',
//     projectId: 'notification-test-20bf1',
//     authDomain: 'notification-test-20bf1.firebaseapp.com',
//     storageBucket: 'notification-test-20bf1.firebasestorage.app',
//     measurementId: 'G-3MDR0361XG',
//   );
// }
